### ISSUE TITLE
快手请求广告失败

### ISSUE THREAD

**Issue by kenkinky** [ifmvo/TogetherAd#47]
```txt
09-09 10:53:24.417 6824-6840/? I/TogetherAd: 初始化穿山甲
09-09 10:53:24.419 6824-6840/? I/TogetherAd: 注册广告提供商：chuan_shan_jia
09-09 10:53:24.536 6824-6840/? I/TogetherAd: 初始化广点通
09-09 10:53:24.537 6824-6840/? I/TogetherAd: 注册广告提供商：guang_dian_tong
09-09 10:53:24.621 6824-6840/? I/TogetherAd: 初始化百青藤
09-09 10:53:24.623 6824-6840/? I/TogetherAd: 注册广告提供商：bai_qing_teng
09-09 10:53:24.693 6824-6840/? I/TogetherAd: 初始化快手
09-09 10:53:24.695 6824-6840/? I/TogetherAd: 注册广告提供商：kuai_shou
09-09 10:53:24.803 6824-6840/? W/System.err:     at com.ifmvo.togetherad.ks.TogetherAdKs.init(TogetherAdKs.kt:56)
09-09 10:53:24.803 6824-6840/? W/System.err:     at com.ifmvo.togetherad.ks.TogetherAdKs.init(TogetherAdKs.kt:35)
09-09 10:53:24.803 6824-6840/? W/System.err:     at com.onyuan.togetherad.App.init(Apk.kt:139)
09-09 10:53:24.812 6824-6840/? I/TogetherAd: 设置默认广告提供商比例：chuan_shan_jia:1,guang_dian_tong:0,bai_qing_teng:0,kuai_shou:0,
09-09 10:53:29.212 6824-6840/? V/TogetherAd: 开始倒计时：8000
09-09 10:53:29.217 6824-6840/? I/TogetherAd: 提供商权重：{chuan_shan_jia=1, guang_dian_tong=0, bai_qing_teng=0, kuai_shou=3}
09-09 10:53:29.233 6824-6840/? I/TogetherAd: 权重最高的是: kuai_shou
09-09 10:53:29.238 6824-6824/? I/TogetherAd: kuai_shou: 开始请求
09-09 10:53:29.238 6824-6824/? I/TogetherAd.allAdListener: 开始请求: 提供商: kuai_shou, 广告位: ad_reward_landscape
09-09 10:53:29.240 6824-6824/? E/TogetherAd: kuai_shou: 请求失败了：null 快手广告SDK初始化失败
09-09 10:53:29.240 6824-6824/? I/TogetherAd: 提供商权重：{chuan_shan_jia=1, guang_dian_tong=0, bai_qing_teng=0, kuai_shou=0}
09-09 10:53:29.240 6824-6824/? I/TogetherAd: 权重最高的是: chuan_shan_jia
09-09 10:53:29.253 6824-6824/? E/TogetherAd.allAdListener: 请求失败: 提供商: kuai_shou, 广告位: ad_reward_landscape, 错误信息: 快手广告SDK初始化失败
09-09 10:53:29.253 6824-6824/? I/TogetherAd: chuan_shan_jia: 开始请求
09-09 10:53:29.253 6824-6824/? I/TogetherAd.allAdListener: 开始请求: 提供商: chuan_shan_jia, 广告位: ad_reward_landscape
```

appId 和 广告位Id 是用的咱demo里面的
用的mumu模拟器测试的, 必现

**Comment by ifmvo** [comment]
模拟器不行，用真机
