### ISSUE TITLE
调用激励广告报错

### ISSUE THREAD

**Issue by lexluthors** [ifmvo/TogetherAd#68]
**Bug 描述和日志**

2023-06-14 17:42:05.906 16255-16325 gdt_ad_mob               E  初始化错误：初始化插件时发生异常
                                                                                                    com.qq.e.comm.managers.plugin.e: Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getFactory(:4)
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:11)
                                                                                                    	at com.qq.e.ads.AbstractAD$1.run(Unknown Source:8)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getFactory(:4) 
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:11) 
                                                                                                    	at com.qq.e.ads.AbstractAD$1.run(Unknown Source:8) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: yaq.pro
                                                                                                    	at com.qq.e.comm.plugin.POFactoryImpl.getInstance(Unknown Source:11)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getFactory(:4) 
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:11) 
                                                                                                    	at com.qq.e.ads.AbstractAD$1.run(Unknown Source:8) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.ExceptionInInitializerError
                                                                                                    	at com.qq.e.comm.plugin.POFactoryImpl.getInstance(Unknown Source:11)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getFactory(:4)
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:11)
                                                                                                    	at com.qq.e.comm.managers.a.run(Unknown Source:6)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.UnsupportedOperationException: unsupport OS version
                                                                                                    	at yaq.pro.<clinit>(pro.java:93)
                                                                                                    	at com.qq.e.comm.plugin.POFactoryImpl.getInstance(Unknown Source:11) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getFactory(:4) 
                                                                                                    	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:11) 
                                                                                                    	at com.qq.e.comm.managers.a.run(Unknown Source:6) 
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
**附加信息**

**Comment by lexluthors** [comment]
@ifmvo 请问这个问题是怎么回事呢？
